#!/usr/bin/env tsx
/**
 * Interactive Migration Setup
 *
 * Collects project-specific configuration before Claude migration begins.
 * Saves configuration to url-mappings.json and .migration-state/setup-config.json.
 *
 * Usage:
 *   npx tsx scripts/setup-migration.ts
 */

import prompts from 'prompts';
import fs from 'fs';
import path from 'path';

// ============================================================================
// Types
// ============================================================================

interface FeatureConfig {
    feature_id: string;
    name: string;
    source_path: string; // URL path appended to source base URL (e.g., "home", "product/123")
    target_path: string; // URL path appended to target base URL (may differ from source)
    sfra_url: string;
    target_url: string;
    selector: string;
    viewport: { width: number; height: number };
    source_config?: {
        dismiss_consent?: boolean;
        consent_button_selector?: string;
    };
    isml_template_path?: string; // Absolute path to ISML template file
}

interface URLMappings {
    version: string;
    source_base_url: string;
    target_base_url: string;
    mappings: FeatureConfig[];
}

interface SetupConfig {
    createdAt: string;
    sourceBaseUrl: string;
    targetBaseUrl: string;
    consentSelector?: string;
    viewport: { width: number; height: number };
    selectedFeatures: string[];
}

// ============================================================================
// Constants
// ============================================================================

const WORKSPACE_ROOT = process.env.WORKSPACE_ROOT || process.cwd();
const STATE_DIR = path.join(WORKSPACE_ROOT, '.migration-state');
const URL_MAPPINGS_FILE = path.join(WORKSPACE_ROOT, 'url-mappings.json');
const SETUP_CONFIG_FILE = path.join(STATE_DIR, 'setup-config.json');

// Directories/files to clean up on reset (generated by downstream scripts)
const GENERATED_ARTIFACTS = {
    directories: [
        path.join(WORKSPACE_ROOT, '.migration-state'),
        path.join(WORKSPACE_ROOT, 'screenshots'),
        path.join(WORKSPACE_ROOT, 'analysis'),
        path.join(WORKSPACE_ROOT, 'sub-plans'),
        path.join(WORKSPACE_ROOT, 'generated'),
    ],
    files: [
        path.join(WORKSPACE_ROOT, 'url-mappings.json'),
        path.join(WORKSPACE_ROOT, 'migration-log.md'),
    ],
};

// Default features to suggest
// Each feature has source_path (SFRA) and target_path (Storefront Next) which may differ
const DEFAULT_FEATURES: Omit<FeatureConfig, 'sfra_url' | 'target_url'>[] = [
    {
        feature_id: '01-homepage-hero',
        name: 'Homepage Hero',
        source_path: 'home',
        target_path: '',
        selector: '.hero, .home-hero, [class*="hero"]',
        viewport: { width: 1920, height: 1080 }
    },
    {
        feature_id: '02-homepage-featured',
        name: 'Featured Products',
        source_path: 'home',
        target_path: '',
        selector: '.featured-products, [class*="featured"]',
        viewport: { width: 1920, height: 1080 }
    },
    {
        feature_id: '03-header-nav',
        name: 'Header Navigation',
        source_path: 'home',
        target_path: '',
        selector: 'header, .header, nav',
        viewport: { width: 1920, height: 1080 }
    },
    {
        feature_id: '04-footer',
        name: 'Footer',
        source_path: 'home',
        target_path: '',
        selector: 'footer, .footer',
        viewport: { width: 1920, height: 1080 }
    },
    {
        feature_id: '05-pdp',
        name: 'Product Detail Page',
        source_path: 'product/25502228M',
        target_path: 'product/25502228M',
        selector: '.pdp, .product-detail, main',
        viewport: { width: 1920, height: 1080 }
    }
];

// ============================================================================
// Utilities
// ============================================================================

function log(msg: string): void {
    console.log(`\x1b[34m[Setup]\x1b[0m ${msg}`);
}

function success(msg: string): void {
    console.log(`\x1b[32m[Setup]\x1b[0m ${msg}`);
}

function warn(msg: string): void {
    console.log(`\x1b[33m[Setup]\x1b[0m ${msg}`);
}

/**
 * Remove all generated artifacts for a clean reset.
 * This centralizes cleanup so downstream scripts don't need to handle it.
 */
function cleanupGeneratedArtifacts(): void {
    log('Cleaning up generated artifacts...');

    // Remove directories (recursively)
    for (const dir of GENERATED_ARTIFACTS.directories) {
        if (fs.existsSync(dir)) {
            fs.rmSync(dir, { recursive: true, force: true });
            log(`  Removed: ${path.relative(WORKSPACE_ROOT, dir)}/`);
        }
    }

    // Remove individual files
    for (const file of GENERATED_ARTIFACTS.files) {
        if (fs.existsSync(file)) {
            fs.unlinkSync(file);
            log(`  Removed: ${path.relative(WORKSPACE_ROOT, file)}`);
        }
    }

    success('Cleanup complete');
}

function loadExistingMappings(): URLMappings | null {
    if (fs.existsSync(URL_MAPPINGS_FILE)) {
        try {
            return JSON.parse(fs.readFileSync(URL_MAPPINGS_FILE, 'utf-8'));
        } catch {
            return null;
        }
    }
    return null;
}

function loadExistingConfig(): SetupConfig | null {
    if (fs.existsSync(SETUP_CONFIG_FILE)) {
        try {
            return JSON.parse(fs.readFileSync(SETUP_CONFIG_FILE, 'utf-8'));
        } catch {
            return null;
        }
    }
    return null;
}

// ============================================================================
// CLI Arguments
// ============================================================================

function parseArgs(): { reset: boolean } {
    const args = process.argv.slice(2);
    return {
        reset: args.includes('--reset'),
    };
}

// ============================================================================
// Main Setup Flow
// ============================================================================

async function main(): Promise<void> {
    const cliArgs = parseArgs();

    console.log('\n\x1b[1m=== Migration Setup ===\x1b[0m\n');

    // Step 1: Check for existing config
    let existingMappings = loadExistingMappings();
    let existingConfig = loadExistingConfig();

    // Handle --reset flag (passed by run-setup.ts orchestrator)
    if (cliArgs.reset) {
        if (existingMappings || existingConfig) {
            warn('Resetting configuration (--reset)...');
            cleanupGeneratedArtifacts();
        }
        existingMappings = null;
        existingConfig = null;
        // Continue to configuration prompts below
    } else if (existingMappings || existingConfig) {
        // Interactive prompt only when running standalone (not via orchestrator)
        const { action } = await prompts({
            type: 'select',
            name: 'action',
            message: 'Existing configuration found. What would you like to do?',
            choices: [
                { title: 'Continue with existing config', value: 'continue' },
                { title: 'Modify existing config', value: 'modify' },
                { title: 'Start fresh', value: 'reset' }
            ]
        });

        if (!action) {
            log('Setup cancelled');
            process.exit(0);
        }

        if (action === 'continue') {
            success('Using existing configuration');
            process.exit(0);
        }

        if (action === 'reset') {
            warn('Resetting configuration...');
            // Clean up all generated artifacts from previous runs
            cleanupGeneratedArtifacts();
            // Clear cached config so defaults are used
            existingMappings = null;
            existingConfig = null;
        }
    }

    // Step 2: Source (SFRA) Configuration
    log('Step 1/4: Source (SFRA) Configuration');

    const sourceConfig = await prompts([
        {
            type: 'text',
            name: 'baseUrl',
            message: 'SFRA base URL (with locale):',
            initial:
                existingMappings?.source_base_url ||
                'https://zzrf-001.dx.commercecloud.salesforce.com/s/RefArchGlobal/en_US/home',
            validate: (v) => v.startsWith('http') || 'Must be a valid URL'
        },
        {
            type: 'text',
            name: 'consentSelector',
            message:
                'Cookie consent button selector (leave empty for auto-detect):',
            initial:
                existingConfig?.consentSelector ||
                '.tracking-consent button.affirm'
        }
    ]);

    if (!sourceConfig.baseUrl) {
        log('Setup cancelled');
        process.exit(0);
    }

    // Step 3: Target Configuration
    log('Step 2/4: Target Configuration');

    const targetConfig = await prompts([
        {
            type: 'text',
            name: 'baseUrl',
            message: 'Target dev server URL:',
            initial:
                existingMappings?.target_base_url || 'http://localhost:5173',
            validate: (v) => v.startsWith('http') || 'Must be a valid URL'
        }
    ]);

    if (!targetConfig.baseUrl) {
        log('Setup cancelled');
        process.exit(0);
    }

    // Step 4: Viewport Configuration
    log('Step 3/4: Viewport Configuration');

    const viewportConfig = await prompts([
        {
            type: 'select',
            name: 'viewport',
            message: 'Default viewport size:',
            choices: [
                {
                    title: 'Desktop (1920x1080)',
                    value: { width: 1920, height: 1080 }
                },
                {
                    title: 'Laptop (1440x900)',
                    value: { width: 1440, height: 900 }
                },
                {
                    title: 'Tablet (768x1024)',
                    value: { width: 768, height: 1024 }
                },
                {
                    title: 'Mobile (375x812)',
                    value: { width: 375, height: 812 }
                }
            ],
            initial: 0
        }
    ]);

    // Step 5: Feature Selection
    log('Step 4/4: Feature Selection');

    // Merge existing features with defaults
    // Construct full URLs from base URL + path
    const existingFeatureIds = new Set(
        existingMappings?.mappings?.map((m) => m.feature_id) || []
    );
    const allFeatures = [
        ...(existingMappings?.mappings || []),
        ...DEFAULT_FEATURES.filter(
            (f) => !existingFeatureIds.has(f.feature_id)
        ).map((f) => ({
            ...f,
            sfra_url: new URL(f.source_path, sourceConfig.baseUrl).toString(),
            target_url: f.target_path
                ? new URL(f.target_path, targetConfig.baseUrl).toString()
                : targetConfig.baseUrl
        }))
    ];

    const { selectedFeatures } = await prompts({
        type: 'multiselect',
        name: 'selectedFeatures',
        message: 'Select features to migrate:',
        choices: allFeatures.map((f) => ({
            title: `${f.feature_id}: ${f.name}`,
            value: f.feature_id,
            selected:
                existingConfig?.selectedFeatures?.includes(f.feature_id) ?? true
        })),
        hint: '- Space to select. Return to submit'
    });

    if (!selectedFeatures || selectedFeatures.length === 0) {
        warn('No features selected. Exiting.');
        process.exit(0);
    }

    // Allow adding custom features
    const { addCustom } = await prompts({
        type: 'confirm',
        name: 'addCustom',
        message: 'Add a custom feature?',
        initial: false
    });

    const customFeatures: FeatureConfig[] = [];
    if (addCustom) {
        let addMore = true;
        while (addMore) {
            const custom = await prompts([
                {
                    type: 'text',
                    name: 'id',
                    message: 'Feature ID (e.g., 06-cart):',
                    validate: (v) =>
                        /^[\w-]+$/.test(v) ||
                        'Use alphanumeric and hyphens only'
                },
                {
                    type: 'text',
                    name: 'name',
                    message: 'Feature name:'
                },
                {
                    type: 'text',
                    name: 'source_path',
                    message: 'Source (SFRA) URL path (e.g., "home", "cart"):',
                    initial: 'home'
                },
                {
                    type: 'text',
                    name: 'target_path',
                    message:
                        'Target URL path (leave empty if same as root, or enter path):',
                    initial: ''
                },
                {
                    type: 'text',
                    name: 'selector',
                    message: 'CSS selector for main content:',
                    initial: 'main'
                }
            ]);

            if (custom.id && custom.name) {
                customFeatures.push({
                    feature_id: custom.id,
                    name: custom.name,
                    source_path: custom.source_path,
                    target_path: custom.target_path,
                    sfra_url: new URL(
                        custom.source_path,
                        sourceConfig.baseUrl
                    ).toString(),
                    target_url: custom.target_path
                        ? new URL(
                              custom.target_path,
                              targetConfig.baseUrl
                          ).toString()
                        : targetConfig.baseUrl,
                    selector: custom.selector,
                    viewport: viewportConfig.viewport
                });
                selectedFeatures.push(custom.id);
            }

            const { more } = await prompts({
                type: 'confirm',
                name: 'more',
                message: 'Add another custom feature?',
                initial: false
            });
            addMore = more;
        }
    }

    // Build final mappings
    const finalMappings: URLMappings = {
        version: '1.0',
        source_base_url: sourceConfig.baseUrl,
        target_base_url: targetConfig.baseUrl,
        mappings: [
            ...allFeatures
                .filter((f) => selectedFeatures.includes(f.feature_id))
                .map((f) => ({
                    ...f,
                    sfra_url: f.sfra_url || sourceConfig.baseUrl,
                    target_url: f.target_url || targetConfig.baseUrl,
                    source_config: sourceConfig.consentSelector
                        ? {
                              dismiss_consent: true,
                              consent_button_selector:
                                  sourceConfig.consentSelector
                          }
                        : undefined
                })),
            ...customFeatures
        ]
    };

    const finalConfig: SetupConfig = {
        createdAt: new Date().toISOString(),
        sourceBaseUrl: sourceConfig.baseUrl,
        targetBaseUrl: targetConfig.baseUrl,
        consentSelector: sourceConfig.consentSelector || undefined,
        viewport: viewportConfig.viewport,
        selectedFeatures
    };

    // Save configuration
    fs.mkdirSync(STATE_DIR, { recursive: true });
    fs.writeFileSync(URL_MAPPINGS_FILE, JSON.stringify(finalMappings, null, 2));
    fs.writeFileSync(SETUP_CONFIG_FILE, JSON.stringify(finalConfig, null, 2));

    success('\nConfiguration saved:');
    console.log(`  - ${URL_MAPPINGS_FILE}`);
    console.log(`  - ${SETUP_CONFIG_FILE}`);
    console.log(`\n  Features: ${selectedFeatures.length} selected`);
    console.log(`  Source: ${sourceConfig.baseUrl}`);
    console.log(`  Target: ${targetConfig.baseUrl}`);

    console.log('\n\x1b[32mSetup complete!\x1b[0m Next steps:');
    console.log('  1. Run: npx tsx scripts/analyze-features.ts');
    console.log('  2. Run: npx tsx scripts/generate-plans.ts');
    console.log('  3. Run: npx tsx scripts/init-migration-log.ts\n');
}

main().catch((err) => {
    console.error('[Setup] Error:', err);
    process.exit(1);
});
