#!/usr/bin/env tsx
/**
 * Interactive Migration Setup (v2)
 *
 * Reads url-mappings.json, prompts the user to confirm/edit page-level config
 * (URLs, ISML paths, consent selector), select which routes to migrate,
 * and writes the result back with `selected` flags.
 *
 * Usage:
 *   npx tsx scripts/setup-migration.ts
 *   npx tsx scripts/setup-migration.ts --reset
 */

import prompts from 'prompts';
import fs from 'fs';
import path from 'path';

// ============================================================================
// Types (match discover-features-claude.ts exactly)
// ============================================================================

interface PageConfig {
    page_id: string;
    name: string;
    description?: string;
    selected?: boolean;
    sfra_url: string;
    target_url: string;
    isml_template: string;
    viewport?: { width: number; height: number };
    source_config?: {
        dismiss_consent?: boolean;
        consent_button_selector?: string;
    };
}

interface URLMappingsV2 {
    version: string;
    description?: string;
    source_base_url: string;
    target_base_url: string;
    sfra_templates_base: string;
    slots_xml_path: string;
    pages: PageConfig[];
}

// ============================================================================
// Constants
// ============================================================================

const WORKSPACE_ROOT = process.env.WORKSPACE_ROOT || process.cwd();
const URL_MAPPINGS_FILE = path.join(WORKSPACE_ROOT, 'url-mappings.json');

// Directories/files to clean up on reset (generated by downstream scripts)
const GENERATED_ARTIFACTS = {
    directories: [
        path.join(WORKSPACE_ROOT, 'screenshots'),
        path.join(WORKSPACE_ROOT, 'analysis'),
        path.join(WORKSPACE_ROOT, 'sub-plans'),
        path.join(WORKSPACE_ROOT, 'migration-plans'),
        path.join(WORKSPACE_ROOT, 'plans'),
    ],
    files: [
        path.join(WORKSPACE_ROOT, 'migration-log.md'),
    ],
};

// ============================================================================
// Utilities
// ============================================================================

function log(msg: string): void {
    console.log(`\x1b[34m[Setup]\x1b[0m ${msg}`);
}

function success(msg: string): void {
    console.log(`\x1b[32m[Setup]\x1b[0m ${msg}`);
}

function warn(msg: string): void {
    console.log(`\x1b[33m[Setup]\x1b[0m ${msg}`);
}

function cleanupGeneratedArtifacts(): void {
    log('Cleaning up generated artifacts...');

    for (const dir of GENERATED_ARTIFACTS.directories) {
        if (fs.existsSync(dir)) {
            fs.rmSync(dir, { recursive: true, force: true });
            log(`  Removed: ${path.relative(WORKSPACE_ROOT, dir)}/`);
        }
    }

    for (const file of GENERATED_ARTIFACTS.files) {
        if (fs.existsSync(file)) {
            fs.unlinkSync(file);
            log(`  Removed: ${path.relative(WORKSPACE_ROOT, file)}`);
        }
    }

    success('Cleanup complete');
}

function loadMappings(): URLMappingsV2 | null {
    if (!fs.existsSync(URL_MAPPINGS_FILE)) return null;
    try {
        const content = JSON.parse(fs.readFileSync(URL_MAPPINGS_FILE, 'utf-8'));
        if (content.version === '2.0' && content.pages) {
            return content;
        }
        warn('url-mappings.json is not version 2.0. Expected v2 schema.');
        return null;
    } catch {
        return null;
    }
}

function saveMappings(mappings: URLMappingsV2): void {
    fs.writeFileSync(URL_MAPPINGS_FILE, JSON.stringify(mappings, null, 2) + '\n');
}

function createSkeletonMappings(): URLMappingsV2 {
    return {
        version: '2.0',
        description: 'Page-level URL mappings for SFRA to Storefront Next migration.',
        source_base_url: 'https://example.com/s/SiteID/en_US',
        target_base_url: 'http://localhost:5173',
        sfra_templates_base: 'storefront-reference-architecture/cartridges/app_storefront_base/cartridge/templates/default',
        slots_xml_path: 'slots/slots.xml',
        pages: [],
    };
}

// ============================================================================
// CLI Arguments
// ============================================================================

function parseArgs(): { reset: boolean } {
    const args = process.argv.slice(2);
    return {
        reset: args.includes('--reset'),
    };
}

// ============================================================================
// Main Setup Flow
// ============================================================================

async function main(): Promise<void> {
    const cliArgs = parseArgs();

    console.log('\n\x1b[1m=== Page Configuration ===\x1b[0m\n');

    // Load url-mappings.json (the seed / single source of truth)
    let mappings = loadMappings();

    if (!mappings) {
        warn('url-mappings.json not found or invalid.');
        log('Creating skeleton — edit the generated file or run `git checkout url-mappings.json` to restore defaults.');
        mappings = createSkeletonMappings();
        saveMappings(mappings);
    }

    // Handle --reset
    if (cliArgs.reset) {
        warn('Resetting generated artifacts (--reset)...');
        cleanupGeneratedArtifacts();
    } else {
        // Check if downstream artifacts already exist — offer to keep or reset
        const hasArtifacts = GENERATED_ARTIFACTS.directories.some(d => fs.existsSync(d))
            || GENERATED_ARTIFACTS.files.some(f => fs.existsSync(f));

        if (hasArtifacts) {
            const { action } = await prompts({
                type: 'select',
                name: 'action',
                message: 'Existing migration artifacts found. What would you like to do?',
                choices: [
                    { title: 'Continue (keep artifacts, update config)', value: 'continue' },
                    { title: 'Reset (clean artifacts, reconfigure)', value: 'reset' },
                    { title: 'Exit (no changes)', value: 'exit' },
                ],
            });

            if (!action || action === 'exit') {
                log('Setup cancelled');
                process.exit(0);
            }

            if (action === 'reset') {
                cleanupGeneratedArtifacts();
            }
        }
    }

    // ── Step 1/3: Global Settings ──────────────────────────────────────────

    log('Step 1/3: Global Settings');

    const globalConfig = await prompts([
        {
            type: 'text',
            name: 'source_base_url',
            message: 'SFRA base URL:',
            initial: mappings.source_base_url,
            validate: (v: string) => v.startsWith('http') || 'Must be a valid URL',
        },
        {
            type: 'text',
            name: 'target_base_url',
            message: 'Target dev server:',
            initial: mappings.target_base_url,
            validate: (v: string) => v.startsWith('http') || 'Must be a valid URL',
        },
    ]);

    if (!globalConfig.source_base_url) {
        log('Setup cancelled');
        process.exit(0);
    }

    mappings.source_base_url = globalConfig.source_base_url;
    mappings.target_base_url = globalConfig.target_base_url;

    // ── Step 2/3: Per-Page Config ──────────────────────────────────────────

    log('Step 2/3: Page Config');

    for (const page of mappings.pages) {
        console.log(`\n  \x1b[1m── ${page.name} (${page.page_id}) ──\x1b[0m`);

        const pageEdits = await prompts([
            {
                type: 'text',
                name: 'sfra_url',
                message: 'SFRA URL:',
                initial: page.sfra_url,
            },
            {
                type: 'text',
                name: 'target_url',
                message: 'Target URL:',
                initial: page.target_url,
            },
            {
                type: 'text',
                name: 'isml_template',
                message: 'ISML template:',
                initial: page.isml_template,
            },
            {
                type: 'text',
                name: 'consent_selector',
                message: 'Consent selector:',
                initial: page.source_config?.consent_button_selector || '',
            },
        ]);

        if (pageEdits.sfra_url !== undefined) page.sfra_url = pageEdits.sfra_url;
        if (pageEdits.target_url !== undefined) page.target_url = pageEdits.target_url;
        if (pageEdits.isml_template !== undefined) page.isml_template = pageEdits.isml_template;

        if (pageEdits.consent_selector) {
            page.source_config = {
                dismiss_consent: true,
                consent_button_selector: pageEdits.consent_selector,
            };
        } else if (pageEdits.consent_selector === '') {
            // User explicitly cleared — remove consent config
            delete page.source_config;
        }
    }

    // ── Step 3/3: Route Selection ──────────────────────────────────────────

    log('Step 3/3: Select Routes to Migrate');

    const { selectedPageIds } = await prompts({
        type: 'multiselect',
        name: 'selectedPageIds',
        message: 'Select pages to migrate:',
        choices: mappings.pages.map(p => ({
            title: `${p.name} (${p.page_id})`,
            value: p.page_id,
            selected: p.selected !== false,
        })),
        hint: '- Space to select. Return to submit',
    });

    if (!selectedPageIds || selectedPageIds.length === 0) {
        warn('No pages selected. Exiting.');
        process.exit(0);
    }

    // Persist selected state
    const selectedSet = new Set<string>(selectedPageIds);
    for (const page of mappings.pages) {
        page.selected = selectedSet.has(page.page_id);
    }

    // ── Write back ─────────────────────────────────────────────────────────

    saveMappings(mappings);

    success('\nConfiguration saved to url-mappings.json');
    console.log(`  Source: ${mappings.source_base_url}`);
    console.log(`  Target: ${mappings.target_base_url}`);
    console.log(`  Pages: ${selectedPageIds.length} selected`);

    for (const page of mappings.pages) {
        const marker = page.selected ? '\x1b[32m✓\x1b[0m' : '\x1b[2m○\x1b[0m';
        console.log(`    ${marker} ${page.name} (${page.page_id})`);
    }

    console.log('');
}

main().catch((err) => {
    console.error('[Setup] Error:', err);
    process.exit(1);
});
